### ISSUE TITLE
Key names in photon stream json format -- discussion

### ISSUE THREAD

**Issue by relleums** [fact-project/photon_stream#1]
Dear all,

the topic of key names is always a hot one and causes sometimes joy but most often rage and destruction.
Personally, I want the photon stream format for FACT to be easy to understand for new FACTie. I never again want to tell a new student, "Ah yes you can of course not understand this key because it is some ancient sh*** and you now need my secret knowledge". For the first time we store (all) our data in an actual file format ```jsonl.gz``` and have the chance to get rid of the daemons of our past.

```YYYYmmdd_RRR_passXXX_phs.jsonl.gz```

| current | proposal | description |
|---|---|---|
|NIGHT | Night | the unique night integer ```YYYYmmdd``` |
|RUNID | Run | the unique run id integer |
| EventNum | Event | the unique event id integer in a run |
| UnixTimeUTC | UnixTime_s_us | an array of two integers [s, us], UnixTime is [defined](https://en.wikipedia.org/wiki/Unix_time) in UTC|
| TriggerType | Trigger | the unique trigger reason id integer |
| ZdPointing | Zd_deg | telescope pointing zenith distance in deg |
| AzPointing | Az_deg | telescope pointing azimuth w.r.t north in deg |
| PhotonArrivals | PhotonArrivals_500ps | a (CHID) list of list containing each photons arrival time slice |
| timeOverThresholdSet | SaturatedPixels | a list of saturated pixel CHIDs |

in a separate file ```YYYYmmdd_RRR_passXXX_bsl.jsonl.gz```

| current | proposal | description |
|---|---|---|
| CentiBaseLines | BaseLines_cpe  | a fix length (CHID) list of the baseline amplitides in centi photon amplitudes |

The baseline files again contains the same night, run and event id representation as the primary file.

CHID is the Continuous Hardware ID of the FACT pixels.
Just as a side remark, each ```char``` in the keys will affect the foreseen output size by 1GByte.

What do you think? Comment below.

**Comment by tarrox** [comment]
If having additional chars is having such an effect on the output size, my question would be whether you want to add type information (like _deg or Unix) to the keys. Or whether you want to save them separately in a json schema file (which would be a good way to describe the data format anyway).

Also isn't night just the date, why not call it that?

**Comment by relleums** [comment]
Thanks for the comment on json schema. Dont worry too much about the size aspect. 1GB does not hurt much when we write 10TB in total. Unfortunately the concept of Night is very different from Date since Night is increasing in mid day at 12:00 and not at 00:00.

**Comment by relleums** [comment]
pass4 is out now, thanks for comments
