### ISSUE TITLE
RuntimeWarning sqrt muon extraction

### ISSUE THREAD

**Issue by relleums** [fact-project/photon_stream#24]
/home/travis/virtualenv/python3.5.4/lib/python3.5/site-packages/photon_stream/muons/tools.py:36:
    RuntimeWarning: invalid value encountered in sqrt
    x = np.sqrt(r1**2 - r2**2)

this creates rather large stdout warnings during muon extraction

**Comment by Laurits7** [comment]
will have a look now

**Comment by relleums** [comment]
This issue is moved to the muon repository
