### ISSUE TITLE
A LOT of Warnings during test

### ISSUE THREAD

**Issue by maxnoe** [fact-project/photon_stream#45]
Running the tests results in 601 warnings because of things like invalid values in sqrt or division by zero and matplotlib.

**Comment by relleums** [comment]
Oh yeah, I see what you mean. It happens during the muon ring search. This is a problem, as it clutters the py.test output.

**Comment by relleums** [comment]
duplicate #24

**Comment by relleums** [comment]
The issue still exists, but this report is a duplicate, see #24
