### ISSUE TITLE
Do not set matplotlib backend in code

### ISSUE THREAD

**Issue by maxnoe** [fact-project/photon_stream#46]
This does seldom work when other stuff was imported first and there is a better option:

Set it using the environmentvariable `MPLBACKEND=Agg`

**Comment by relleums** [comment]
I see your point.
Is this about this line here?

https://github.com/fact-project/photon_stream/blob/7f1feafbcb0f8aabe1580211a590b7eb8bedf82c/photon_stream/tests/test_plotting_api.py#L10

**Comment by dneise** [comment]
I think so, yes
