### ISSUE TITLE
Test fail, production, Lock-File (creation or existence)

### ISSUE THREAD

**Issue by relleums** [fact-project/photon_stream#66]
Tests fail. Sth. has changed in the libraries used by the photon_stream

```python
    def status(
        obs_dir=join('/gpfs0', 'fact', 'processing', 'public', 'phs', 'obs'),
        max_jobs_in_qsub=256,
        queue=QUEUE_NAME,
        runs_in_qstat=None
    ):
        print('Start status')
    
        runstatus_path = join(obs_dir, 'runstatus.csv')
        runstatus_lock_path = join(obs_dir, '.lock.runstatus.csv')
        tmp_status_dir = join(obs_dir, '.tmp_status')
        obs_std_dir = obs_dir+'.std'
    
        assert exists(runstatus_path)
>       assert exists(runstatus_lock_path)
E       AssertionError
../../../virtualenv/python3.5.4/lib/python3.5/site-packages/photon_stream/production/isdc/_status.py:38: AssertionError
```

**Comment by relleums** [comment]
I have no idea what is going on yet. In the test_production it calls ranstatus.init() and immediately asserts that the folder and lock-file were created. This assertion passes. In the very next call, the production.isdc.status fails to assert that the lock-file exists.

**Comment by relleums** [comment]
On my machine, the master and its tests do pass

```
sebastian@1337Pad:~/Desktop/phd/FACT/single_photons/photon_stream$ py.test photon_stream/tests/test_production.py 
================================================ test session starts =================================================
platform linux -- Python 3.5.4, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/sebastian/Desktop/phd/FACT/single_photons/photon_stream, inifile:
collected 1 item                                                                                                      

photon_stream/tests/test_production.py .

============================================== 1 passed in 6.40 seconds ==============================================
```
Here Python, pytest, py and pluggy have the same version as on travis

**Comment by relleums** [comment]
It is about filelock.
We used to develop on filelock version '2.0.7'. Now there is filelock version '3.0.0'

I think, I used filelock not exactly correct in the past.
I used to create the lockfile myself, and at the end of FileLock.acquire(), the lock file was not deleted.

In version '3.0.0', the lock file is deleted in the end of FileLock.acquire().

The solution is probably, to not create the lock file manually, and to not assert manually that it exists.

**Comment by dneise** [comment]
Ah, so the test did not pass, but the application still works?

**Comment by relleums** [comment]
The test had an assertion that the lock file exists AND the status() function had an assertion that the lock file exists. So before this pull request, the photon-stream production failed when using filelock '3.0.0'.

**Comment by relleums** [comment]
fixed
