### ISSUE TITLE
The FACT data tree

### ISSUE THREAD

**Issue by relleums** [fact-project/photon_stream#7]
The FACT data tree
------------------

The various types of data of the FACT collaboration are bulky and inaccessible to large fractions of the collaboration. Scattered on different clusters with different access policies there is no way for a new student to participate. The photon-stream allows to reduce the observation and simulation event data by almost two orders of magnitude. Here I want to make use of this reduction to help us and upcoming students to access and analyse FACT observations. We already have a large photon-stream pass, but at the moment nobody knows where to find it.

User-story
-------------
On our start page ```http://www.fact-project.org``` a student browses the link ```http://www.fact-project.org/data``` to explore and perform an analysis for FACT. She gets redirected to a simple https server running on one of our clusters (e.g. Phido). The web server serves her just a plain file system tree. I think of a simple setup like we use it for e.g. the [overview videos](http://fact-project.org/overview_video/2017/05/03/). She does only need the 'common' FACT credentials but no specific cluster account. In the file system tree she finds:

- The observation data runs in photon-stream format in its common year/month/night pattern
- A run-info-database
- The auxillary files of the FACT telescope in its common year/month/night pattern
- The simulated data runs in photon-stream format
- A simulation-settings-database
- README.md files to provide fundamental guiding.

The FACT data tree might look like this:

- http://www.fact-project.org/data/pass4/
    - observations/
        - e.g. 2017/03/12/20170312_phs.jsonl.gz
    - simulations/
        - e.g. proton_klaus/123456_sim_phs.jsonl.gz

The databases might be just plain json (or similar) blobs.
Now the student can already get started and 'browse' the relevant data for his analysis. She might use wget or request to download the data from within her analysis program. Of course the student would not run her full analysis like this, but she could do so. When she gets access to phido, she finds there the exact same filesystem tree to run all her programs and does not need to adopt.

Suggestion
----------------------------
We restrict ourselves to passes. The current and first photon-stream production pass is Pass4.
This means, that all the raw data was processed into the photon-stream with the same shitty extractor.
If we ever find time and joy to have a better extractor, this will be Pass5 and so on. We can try to add from time to time the latest raw-data in the Pass4 photon-stream format.
The photon-stream observation runs are (will have to be) created at ISDC, the photon-stream simulation runs are (will have to be) created at Phido. The processed files are then moved to our FACT data tree.
In the FACT data tree, we frequently run a [tool](https://github.com/fact-project/photon_stream/blob/master/photon_stream/production/status.py) to estimate the completeness of the pass.

Questions
---------
- What else do we need? What is missing for a student to start with an analysis.

- How should we offer the run-info and the simulation-settings data-bases? There were already suggestions made to strip down fields of the std. run-info-db and provide to the user only the runs which are actually present in the pass, and use a second database for the completness status of the pass. I think a simple blob (hdf5,json,etc...) would be fine.

- Do we have the infrastructure for this? At ETH we have both the storage space (I estimate we might need up to 20TBytes) and the open access to run a webserver. But ETH has no computing power. So I would opt for the Phido.

- Shall we backup the whole thing? We could do backups at ETH and at ISDC.

- This whole project involves some scripts and rsyncs to run. Where should we put these? I suggest to have ALL scripts (the ones used at ISDC, the ones from Phido, the web server settings, and even the redirect on fact-project.org) in one repository. Maybe inside the photo-stream repo? Maybe the whole photon-stream repo should be in pyfact?

- Shall we have some telcons to evaluate our options?

Need help
---------
So far this is only a dream, but I think we are at the dawn to make this happen. Currently I am in a mindset of keeping everything as simple as possible and willingly not foreseeing any future flexibility. I am open for alternative solutions. I do not want a solution to satisfy my needs, but a solution to cover the largest common set of data access for all of us.

```
I have a user-story that one day this collaboration will rise up, and live out the true meaning of its creed: ‘We hold these truths to be self-evident: that all students have equal and easy access to the data.’
```

**Comment by dneise** [comment]
>  We can try to add from time to time the latest raw-data in the Pass4 photon-stream format.

I foresee (or fear) that this ecosystem of accessible data will wither and die if the data people are interested in is not available here, but are only available as bulky "raw"-files that need to be treated differently.

It is a matter of building trust if you will, new students cannot afford to set up their own analysis if they cannot be sure enough to find the data they need in this ecosystem. If they have to choose between being able to access all the data (potentially!) and having easy access to only part of the data, they might be too easily pressed to what I believe is the wrong decision. 

If we however "swear" to always at least try to convert the most recent data also into the currently "active" pass (which is pass4 at the moment), then said students need not fear to suddenly loose the ground their analysis is based on.

**Comment by relleums** [comment]
Currently the biggest chunk of FACT events in an online storage is the photon-stream (about 75%).  Maybe you are right, and there must be an automatic production for the latest runs of last night before we can even start offering the existing runs. I wanted to get going now and handle this topic later, but apparently it is more important. I have to find a way to set this up between ISDC and PhiDo and ETH as a backup. Of course ideas and help wanted.

**Comment by dneise** [comment]
Get going now and handle it later is fine. 

I just under stood "We can try ..." as "will probably not be done".

**Comment by relleums** [comment]
The automatic processing is running now and fact-project.org/data ir reality.
