### ISSUE TITLE
What does 'flatten' do?

### ISSUE THREAD

**Issue by kbruegge** [fact-project/photon_stream#8]
I'm a bit confused by the output of the `flatten` method of an events photon_stream. 
It returns a matrix which has dimensions Nx3 where N is the total number of photons in the event.

```
In [20]: event.photon_stream.flatten?
Signature: event.photon_stream.flatten()
Docstring: <no docstring>
File:      ~/.anaconda3/lib/python3.5/site-packages/photon_stream/PhotonStream.py
Type:      method

In [21]: event.photon_stream.flatten
Out[21]: <bound method PhotonStream.flatten of PhotonStream(1440 time lines, 6413 photons)>

In [22]: event.photon_stream.flatten()
Out[22]: 
array([[  3.40899581e-01,   2.06615107e+00,   2.19999994e-08],
       [  3.97714551e-01,   2.16374893e+00,   3.24999991e-08],
       [  3.97714551e-01,   1.96740663e+00,   2.34999993e-08],
       ..., 
       [ -5.68172225e-02,   2.16374893e+00,   5.24999985e-08],
       [ -5.68172225e-02,   2.16374893e+00,   6.14999983e-08],
       [ -5.68172225e-02,   1.96740663e+00,   5.74999984e-08]])

In [23]: _.shape
Out[23]: (6413, 3)
```

**Comment by relleums** [comment]
The name ```flatten()``` is indeed very generic and should be changed. I added a docstring now to at least help a bit. Point is, there are different representation for the photon-stream in computer memory. The list-of-lists style which is used in the storage jsonl and experimental binary are very compact and thus used for storage. An alternative representation is returned by this flatten(). It is a list where each photon is represented as a 3D point in the space of x-direction [deg], y-direction [deg] and arrival time [s]. In total I have used so far these three representations:

- Lists-of-Lists representation. Very good for compact storage
- List-of-3D-points representation. Ideal for plotting and density clustering using e.g. dbscan
- 2D-matrix-of-pixels-X-time-slices representation. Each entry in the matrix is the number count of photons in a pixel at a certain time slice. This is very useful for fast slicing in time.

Maybe we should rename ```flatten()``` to e.g. ```to_3d_points_in_xdir_ydir_time()```

**Comment by kbruegge** [comment]
>  It is a list where each photon is represented as a 3D point in the space of x-direction [deg], y-direction [deg] and arrival time [s].

Ah yes. That's what I guessed. I just wasn't sure about the units there. Thanks for clarifying.

> 2D-matrix-of-pixels-X-time-slices representation. Each entry in the matrix is the number count of photons in a pixel at a certain time slice. This is very useful for fast slicing in time.

This is great. I'm currently using the same representation. I create it by hand in a very ugly, and painfully slow, manner like this:

```
            l = json.loads(f.readline().decode('utf-8'))['PhotonArrivals_500ps']
            a = np.zeros((1440, 100), dtype=np.float32)
            for k, p in enumerate(l):
                mask = np.array(p)-slice_offset
                for e in mask:
                    a[k][e] += 1
```
Is there a faster way? Or is there even already a method in here that provides this representation?

**Comment by relleums** [comment]
> Is there a faster way? Or is there even already a method in here that provides this representation?

No there is not.

> painfully slow

All python operations on this list of list structure are unfortunately crazy slow. I just entered the cython world and have actually implement this for a similar project to solve a similar problem. If the suffer pressure will be high enough and we know that we want a hand full of functions to be faster, I will implement them in cython.

Maybe it would be good to have the ```list-of-lists-2-three-dimensional-points``` and the ```list-of-lists-2-two-dimensional-fixed-length-matrix``` in a fast ```c``` extension.

**Comment by relleums** [comment]
In the meantime, I found other (hopefully better) names to describe the different representations. I even made a module dedicated to this.
