### ISSUE TITLE
Possible change of 3rd party library caused fail of muon detection test

### ISSUE THREAD

**Issue by relleums** [fact-project/photon_stream#83]
Not strictly related to the photon-stream.
The test for the muon extraction fails without any changes coming from our site.
We will have a look.
Of course this also shows that the muon stuff should be moved out of the basic photon-stream repo.

**Comment by dneise** [comment]
If you are using continous integration tests on travis, you can switch on a weekly/monthly cron-job testing your master branch. This way you at least realize if tests fails due to upstream changes by 3rd libs.

https://docs.travis-ci.com/user/cron-jobs/

**Comment by relleums** [comment]
Laurits andI conclude that the muon package should be removed from the photon-stream package anyhow. It is a package for a specific analysis that just uses the photon-stream. There is no point in bothering the other users of the photon-stream with the problems of the muons. So I think we will 'solve' this issue for the photon-stream by moving the issue and code to the [muon repository](https://github.com/fact-project/muons) which I already created to host this code.

**Comment by relleums** [comment]
This issue is moved now into the muon repository.
