### ISSUE TITLE
Warnings when importing

### ISSUE THREAD

**Issue by kbruegge** [fact-project/photon_stream#9]
Maybe not a bug but somewhat weird nonetheless. When import photon_stream I get errors related to some GUI frameworks. I guess most likely related to some MacOS related matplotlib backend foo.
So I guess this is just some messed up configuration on my end. 
However I'm wondering if dependency to the plotting stuff is needed when one only wants to read the data. 

```

In [1]: import photon_stream as ps
objc[30872]: Class TKApplication is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/mackaiver/.anaconda3/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[30872]: Class TKMenu is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/mackaiver/.anaconda3/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[30872]: Class TKContentView is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/mackaiver/.anaconda3/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[30872]: Class TKWindow is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/mackaiver/.anaconda3/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.

```

**Comment by relleums** [comment]
I have not seen this yet, (not even at nightmare ISDC), but I can understand your point here as fragile dependencies are always a pain: ```However I'm wondering if dependency to the plotting stuff is needed when one only wants to read the data.```. So somehow the package needs to be split in two parts right? plotting needs to be separated. Any suggestions here? Do you know an example package  or good practice pattern to look at?

**Comment by kbruegge** [comment]
Not an expert on good practices in Python. However my gut feeling tells me that another module that provides methods to plot an *event* could be helpful. Something like this maybe:

```
import photon_stream.stream as ps  #no plotting stuff imported in here
import photon_stream.plotter as ps_plotter # some plotting functionality

run = ps.Run('20151001_011.phs.jsonl.gz')
event = next(run)
ps_plotter.3d_plot(event)
ps_plotter.other_awesome_plot(event)
```

Maybe our in-house pythonista @MaxNoe could chip in here.

**Comment by relleums** [comment]
I like this idea: 

```
import photon_stream.stream as ps  #no plotting stuff imported in here
import photon_stream.plotter as ps_plotter # some plotting functionality
```
